FROM node:20-alpine as build
WORKDIR /app
COPY cctv-frontend/ ./
RUN npm ci
RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/cctv-frontend/ /usr/share/nginx/html/
COPY cctv-frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]