version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: cctv-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - cctvnet

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: cctv-backend
    ports:
      - "5050:5050"
    networks:
      - cctvnet

networks:
  cctvnet:
    driver: bridge
