server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    
    # Debug y permisos
    error_log /var/log/nginx/error.log debug;
    access_log /var/log/nginx/access.log;

    # Servir archivos estáticos de Angular
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        # Para debug
        add_header X-Debug-Root $document_root;
        add_header X-Debug-URI $uri;
    }

    # Proxy API requests to backend (Flask)
    location /video {
        proxy_pass http://backend:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /cameras {
        proxy_pass http://backend:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /video-frame {
        proxy_pass http://backend:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
